version: '2'

services:

  mp-fwd:
    build: ./mp-fwd
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  gatewayrs:
    build: ./hm-gatewayrs
    expose:
      - "1680"   
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:

