version: '2'

services:

  # client
  mpfwd:
    build: ./mp-fwd
    privileged: true
    network_mode: host 
    volumes:
      - 'pktfwdr:/var/pktfwd'

  # "server"
  gatewayrs:
    build: ./hm-gatewayrs
    network_mode: host
    expose:
      - "1680"   
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:

