version: '2'

services:

  mp-fwd:
    build: ./mp-fwd
    privileged: true
    network_mode: host 
    volumes:
      - 'pktfwdr:/var/pktfwd'

  gatewayrs:
    build: ./hm-gatewayrs
    network_mode: host
    expose:
      - "1680"   
    # ports:
    #   - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:

